# permissions for end users to view designateapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: designateapi-viewer-role
rules:
- apiGroups:
  - designate.openstack.org
  resources:
  - designateapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - designate.openstack.org
  resources:
  - designateapis/status
  verbs:
  - get
