apiVersion: designate.openstack.org/v1beta1
kind: DesignateAPI
metadata:
  name: designate
spec:
  # TODO(user): Add fields here
  databaseInstance: openstack
  databaseUser: designate
  serviceUser: designate
  containerImage: quay.io/tripleowallabycentos9/openstack-designate-api:current-tripleo
  replicas: 1
  secret: osp-secret
  debug:
    dbSync: false
    service: false
  preserveJobs: false
  nodeSelector: {}
  customServiceConfig: |
    [DEFAULT]
    debug: true
  resources:
    requests:
      memory: "500Mi"
      cpu: "1.0"
