apiVersion: designate.openstack.org/v1beta1
kind: DesignateAPI
metadata:
  name: designateapi
  namespace: openstack
spec:
  # TODO(user): Add fields here
  databaseInstance: openstack
  serviceUser: designate
  databaseUser: designate
  preserveJobs: false
  replicas: 1
  secret: osp-secret
  containerImage: quay.io/tripleowallabycentos9/openstack-designate-api:current-tripleo
  debug:
    dbSync: false
    service: false
  # passwordSelector: a map of passwords types to keys names within the secret - not implemented yet.
  nodeSelector: {}
  customServiceConfig: |
    [DEFAULT]
    debug: true
  resources:
    requests:
      memory: "500Mi"
      cpu: "1.0"

